Improve exception handling in Persistit
Instead of catching native PersistitExceptions and throwing new
PermanentStorageException(e.toString()), include the whole causative
exception: PermanentStorageException(e).  I made this change after a
Travis CI failure where one of the PersistitExceptions carried a null
message, making it useless in the absence of its stack trace.